# Generated by Django 3.0.5 on 2020-04-14 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_id', models.CharField(max_length=255)),
                ('hashed_name', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('original_meta_data', models.TextField(null=True)),
                ('original_size', models.IntegerField(help_text='The size, in bytes, of the uploaded file.', null=True)),
                ('original_charset', models.CharField(max_length=255, null=True)),
                ('bucket', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileTransactionLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.FileStorage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
