# Generated by Django 3.0.5 on 2020-04-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filestorage',
            name='hashed_id',
        ),
        migrations.AlterField(
            model_name='filestorage',
            name='hashed_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
