# Generated by Django 3.0.5 on 2020-04-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_filestorage_server_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filestorage',
            old_name='bucket',
            new_name='bucket_name',
        ),
        migrations.AddField(
            model_name='filestorage',
            name='bucket_raw',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filestorage',
            name='connection_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filestorage',
            name='driver_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
