# Generated by Django 3.0.5 on 2020-04-16 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20200416_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filestorage',
            name='connection_name',
        ),
        migrations.RemoveField(
            model_name='filestorage',
            name='driver_name',
        ),
    ]
